# Generated by Django 4.2.1 on 2023-05-25 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(editable=False, max_length=200, verbose_name='اسلاگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='تصویر دسته بندی')),
                ('category_parent', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sub_category', to='product.category', verbose_name='دسته بندی اصلی')),
            ],
            options={
                'verbose_name': 'دسته بندی محصولات',
                'verbose_name_plural': 'دسته بندی محصولات',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('type', models.CharField(blank=True, choices=[('c', 'نقدی'), ('p', 'درصدی')], max_length=1, null=True, verbose_name='نوع تخفیف')),
                ('amount', models.IntegerField(verbose_name='تخفیف')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('name', models.CharField(max_length=150, verbose_name='نام محصول')),
                ('slug', models.SlugField(editable=False, max_length=200, verbose_name='اسلاگ')),
                ('short_description', models.TextField(verbose_name='مشخصات')),
                ('detail_description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('stock', models.IntegerField(default=0, verbose_name='موجودی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='product.category', verbose_name='دسته بندی محصول')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_discount', to='product.discount', verbose_name='تخفیف محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصول',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='تصویر')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصویر',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_discount', to='product.discount', verbose_name='تخفیف دسته بندی'),
        ),
    ]
