<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-05-16 18:19

from django.conf import settings
=======
# Generated by Django 4.2.1 on 2023-05-25 20:59

>>>>>>> develop
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> develop
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('is_deleted', models.BooleanField(default=False)),
=======
>>>>>>> develop
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(editable=False, max_length=200, verbose_name='اسلاگ')),
<<<<<<< HEAD
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='تصویر')),
                ('discount_type', models.CharField(blank=True, choices=[('c', 'نقدی'), ('p', 'درصدی'), ('n', 'بدون تخفیف')], default='n', max_length=1, null=True, verbose_name='نوع تخفیف')),
                ('discount_amount', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='تخفیف')),
=======
                ('image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='تصویر دسته بندی')),
                ('category_parent', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sub_category', to='product.category', verbose_name='دسته بندی اصلی')),
>>>>>>> develop
            ],
            options={
                'verbose_name': 'دسته بندی محصولات',
                'verbose_name_plural': 'دسته بندی محصولات',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
=======
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('type', models.CharField(blank=True, choices=[('c', 'نقدی'), ('p', 'درصدی')], max_length=1, null=True, verbose_name='نوع تخفیف')),
                ('amount', models.IntegerField(verbose_name='تخفیف')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> develop
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('name', models.CharField(max_length=150, verbose_name='نام محصول')),
                ('slug', models.SlugField(editable=False, max_length=200, verbose_name='اسلاگ')),
                ('short_description', models.TextField(verbose_name='مشخصات')),
                ('detail_description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
<<<<<<< HEAD
                ('discount_type', models.CharField(blank=True, choices=[('c', 'نقدی'), ('p', 'درصدی'), ('n', 'بدون تخفیف')], default='n', max_length=1, null=True, verbose_name='نوع تخفیف')),
                ('discount_amount', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='تخفیف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('stock', models.IntegerField(default=0, verbose_name='موجودی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Product Categoy')),
=======
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('stock', models.IntegerField(default=0, verbose_name='موجودی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='product.category', verbose_name='دسته بندی محصول')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_discount', to='product.discount', verbose_name='تخفیف محصول')),
>>>>>>> develop
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصول',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
=======
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='تصویر')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product.product', verbose_name='محصول')),
>>>>>>> develop
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصویر',
            },
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('text', models.TextField(max_length=100, verbose_name='نظر')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظر',
                'ordering': ['created_at'],
            },
=======
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_discount', to='product.discount', verbose_name='تخفیف دسته بندی'),
>>>>>>> develop
        ),
    ]
