# Generated by Django 4.2.1 on 2023-05-22 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_image_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='دسته بندی'),
        ),
    ]
