# Generated by Django 4.2.1 on 2023-05-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
        migrations.AddField(
            model_name='product',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='تصویر'),
        ),
    ]
