# Generated by Django 4.2.1 on 2023-05-22 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_image_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product.product', verbose_name='محصول'),
        ),
    ]
