# Generated by Django 4.2.1 on 2023-05-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_discount_delete_comment_category_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='discount',
        ),
    ]
