# Generated by Django 4.2.1 on 2023-05-23 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_category_is_deleted_and_more'),
        ('customers', '0002_user_discount_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='product.product', verbose_name='محصول'),
        ),
    ]
