# Generated by Django 4.2.1 on 2023-05-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'فاکتور', 'verbose_name_plural': 'فاکتور'},
        ),
    ]
