# Generated by Django 4.2.1 on 2023-05-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
