# Generated by Django 4.2.1 on 2023-05-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_delete_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='is_deleted',
        ),
    ]
